"""secondary books-table - BookItem

Revision ID: ec4b4d39a61d
Revises: 96d81c8028d7
Create Date: 2019-05-16 17:07:06.344067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4b4d39a61d'
down_revision = '96d81c8028d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('desription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_item_author'), 'book_item', ['author'], unique=True)
    op.create_index(op.f('ix_book_item_name'), 'book_item', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_item_name'), table_name='book_item')
    op.drop_index(op.f('ix_book_item_author'), table_name='book_item')
    op.drop_table('book_item')
    # ### end Alembic commands ###
